[build]
  command = "chmod +x ./mvnw && ./mvnw clean package -DskipTests"
  publish = "target/classes"
  ignore = "git diff --quiet HEAD^ HEAD ./"

[build.environment]
  JAVA_VERSION = "17"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
