services:
  - type: web
    name: carbon-footprint-calculator
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/carbon-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_VERSION
        value: "21"
      - key: PORT
        value: "8080"

databases:
  - name: carbon_db
    databaseName: carbon_db
    user: carbon_user
    plan: free
