services:
  - type: web
    name: carbon-footprint-calculator
    env: docker
    buildCommand: "./mvnw package -DskipTests"
    startCommand: "java -jar -Dspring.profiles.active=prod target/*.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /actuator/health
    plan: free
    branch: main
    numInstances: 1
    autoDeploy: true
